# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160523_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
